# Generated by Django 5.1.4 on 2025-03-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_birthday_profile_life_expectancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life_expectancy',
            field=models.IntegerField(default=77),
        ),
    ]
