# Generated by Django 5.1.4 on 2025-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='annual', max_length=50, verbose_name='Frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debttemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='annual', max_length=50, verbose_name='Frequency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='annual', max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='incometemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='annual', max_length=50, verbose_name='Frequency'),
        ),
    ]
