# Generated by Django 5.1.4 on 2024-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='growth_application_strategy',
            field=models.CharField(choices=[('start', 'Start'), ('end', 'End')], default='start', max_length=50, verbose_name='Growth Application Strategy'),
        ),
    ]
