# Generated by Django 5.1.4 on 2024-12-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plan_growth_application_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irainvestment',
            name='ira_type',
        ),
        migrations.RemoveField(
            model_name='irainvestmenttemplate',
            name='ira_type',
        ),
        migrations.AddField(
            model_name='irainvestment',
            name='is_contribution_tax_deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irainvestmenttemplate',
            name='is_contribution_tax_deferred',
            field=models.BooleanField(default=False),
        ),
    ]
