# Generated by Django 5.1.4 on 2025-03-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_debt_frequency_debttemplate_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='growth_rate',
        ),
    ]
