# Generated by Django 5.1.4 on 2024-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_planconfig_cash_planconfig_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdeferredinvestmentconfig',
            name='age',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
