# Generated by Django 5.1.4 on 2024-12-12 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_irainvestment_ira_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='CashReserve',
        ),
        migrations.RenameModel(
            old_name='CashTemplate',
            new_name='CashReserveTemplate',
        ),
        migrations.AlterModelOptions(
            name='cashreserve',
            options={'verbose_name': 'Cash Reserve', 'verbose_name_plural': 'Cash Reserves'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='cashes',
            new_name='cash_reserves',
        ),
        migrations.RenameField(
            model_name='plantemplate',
            old_name='cash_template',
            new_name='cash_reserve_templates',
        ),
    ]
