# Generated by Django 5.1.4 on 2024-12-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cash_cashreserve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashreserve',
            old_name='cash_maintenance_strategy',
            new_name='cash_reserve_maintenance_strategy',
        ),
        migrations.RenameField(
            model_name='cashreservetemplate',
            old_name='cash_maintenance_strategy',
            new_name='cash_reserve_maintenance_strategy',
        ),
    ]
