# Generated by Django 5.1.4 on 2024-12-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_taxdeferredinvestmentconfig_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdeferredinvestmentconfig',
            name='age',
        ),
    ]
