# Generated by Django 5.1.4 on 2024-12-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cash_maintenance_strategy_cashreserve_cash_reserve_maintenance_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashreserve',
            old_name='cash_reserve_maintenance_strategy',
            new_name='cash_reserve_strategy',
        ),
        migrations.RenameField(
            model_name='cashreservetemplate',
            old_name='cash_reserve_maintenance_strategy',
            new_name='cash_reserve_strategy',
        ),
    ]
