# Generated by Django 5.1.4 on 2024-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_taxdeferredinvestmentconfig_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planconfig',
            name='retirement_strategy',
            field=models.CharField(choices=[('debt_free', 'Debt-Free'), ('age', 'Age-Based'), ('percent_rule', 'Percentage Rule'), ('target_savings', 'Target Savings')], max_length=50, verbose_name='Retirement Strategy'),
        ),
    ]
