# Generated by Django 5.1.4 on 2024-12-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_cash_reserve_maintenance_strategy_cashreserve_cash_reserve_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreserve',
            name='cash_reserve_strategy',
            field=models.CharField(choices=[('fixed', 'Fixed Cash Reserve'), ('variable', 'Variable Cash Reserve')], max_length=50, verbose_name='Cash Maintenance Strategy'),
        ),
        migrations.AlterField(
            model_name='cashreservetemplate',
            name='cash_reserve_strategy',
            field=models.CharField(choices=[('fixed', 'Fixed Cash Reserve'), ('variable', 'Variable Cash Reserve')], max_length=50, verbose_name='Cash Maintenance Strategy'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('onetime', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('onetime', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
    ]
