# Generated by Django 5.1.4 on 2024-12-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cashreserve_cash_reserve_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=50, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=50, verbose_name='Expense Type'),
        ),
    ]
