# Generated by Django 5.1.4 on 2024-12-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_expense_type_alter_expensetemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
    ]
