# Generated by Django 5.1.4 on 2024-12-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_expense_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokerageinvestmenttemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cashreservetemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='debttemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expensetemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='incometemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='irainvestmenttemplate',
            old_name='template_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='taxdeferredinvestmenttemplate',
            old_name='template_description',
            new_name='description',
        ),
    ]
