# Generated by Django 5.1.4 on 2024-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_plantemplate_brokerage_investment_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='retirement_age',
            field=models.PositiveIntegerField(default=75, help_text='The age at which retirement starts.', verbose_name='Retirement Age'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retirement_income_goal',
            field=models.FloatField(help_text='Annual income goal during retirement.', null=True, verbose_name='Retirement Income Goal'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retirement_savings_amount',
            field=models.FloatField(help_text='Initial savings amount at the time of retirement.', null=True, verbose_name='Retirement Savings Amount'),
        ),
    ]
