# Generated by Django 5.1.4 on 2024-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_plan_retirement_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='retirement_withdrawal_rate',
            field=models.FloatField(help_text='Annual withdrawal rate as a percentage.', null=True, verbose_name='Retirement Withdrawal Rate'),
        ),
    ]
