# Generated by Django 5.1.4 on 2024-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_plan_retirement_withdrawal_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='annual', max_length=50, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='incometemplate',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='annual', max_length=50, verbose_name='Frequency'),
        ),
    ]
