# Generated by Django 5.1.4 on 2024-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_income_frequency_incometemplate_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50, verbose_name='Frequency'),
        ),
    ]
