# Generated by Django 5.1.4 on 2024-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_plan_age_alter_plan_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2024, null=True, verbose_name='Year'),
        ),
    ]
