# Generated by Django 5.1.4 on 2024-12-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_plantemplate_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='expense_type',
        ),
        migrations.RenameField(
            model_name='expensetemplate',
            old_name='type',
            new_name='expense_type',
        ),
    ]
