# Generated by Django 5.1.4 on 2024-12-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_expense_growth_rate_expensetemplate_growth_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='grows_with_inflation',
            field=models.BooleanField(default=False, help_text='Whether the expense grows with inflation.', verbose_name='Grows with Inflation'),
        ),
        migrations.AddField(
            model_name='expensetemplate',
            name='grows_with_inflation',
            field=models.BooleanField(default=False, help_text='Whether the expense grows with inflation.', verbose_name='Grows with Inflation'),
        ),
    ]
