# Generated by Django 5.1.4 on 2024-12-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_expense_grows_with_inflation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdeferredinvestment',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.income', verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='taxdeferredinvestmenttemplate',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.income', verbose_name='Income'),
        ),
    ]
