# Generated by Django 5.1.4 on 2024-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_taxdeferredinvestment_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='allow_negative_disposable_income',
        ),
        migrations.RemoveField(
            model_name='plantemplate',
            name='allow_negative_disposable_income',
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_negative_funds',
            field=models.CharField(choices=[('none', 'None'), ('minimum_only', 'Minimum Only'), ('full', 'Full')], default='none', max_length=50, verbose_name='Allow Negative Funds'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='allow_negative_funds',
            field=models.CharField(choices=[('none', 'None'), ('minimum_only', 'Minimum Only'), ('full', 'Full')], default='none', max_length=50, verbose_name='Allow Negative Funds'),
        ),
    ]
