# Generated by Django 5.1.4 on 2024-12-29 23:52

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_plan_allow_negative_funds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irainvestment',
            name='is_contribution_tax_deferred',
        ),
        migrations.RemoveField(
            model_name='irainvestmenttemplate',
            name='is_contribution_tax_deferred',
        ),
        migrations.CreateModel(
            name='RothIraInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('growth_rate', models.FloatField(help_text='Annual growth rate as a percentage.', verbose_name='Growth Rate')),
                ('initial_balance', models.FloatField(help_text='Initial balance in the IRA account.', verbose_name='Initial Balance')),
                ('contribution_strategy', models.CharField(choices=[('fixed', 'Fixed'), ('percentage_of_income', 'Percentage of Income'), ('max', 'Max')], default='fixed', max_length=50, verbose_name='Contribution Strategy')),
                ('contribution_percentage', models.FloatField(blank=True, help_text='Percentage of income contributed annually.', null=True, verbose_name='Contribution Percentage')),
                ('contribution_fixed_amount', models.FloatField(blank=True, help_text='Fixed amount contributed annually.', null=True, verbose_name='Contribution Fixed Amount')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='edited_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Roth IRA Investment Configuration',
                'verbose_name_plural': 'Roth IRA Investment Configurations',
            },
        ),
        migrations.CreateModel(
            name='RothIraInvestmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('growth_rate', models.FloatField(help_text='Annual growth rate as a percentage.', verbose_name='Growth Rate')),
                ('initial_balance', models.FloatField(help_text='Initial balance in the IRA account.', verbose_name='Initial Balance')),
                ('contribution_strategy', models.CharField(choices=[('fixed', 'Fixed'), ('percentage_of_income', 'Percentage of Income'), ('max', 'Max')], default='fixed', max_length=50, verbose_name='Contribution Strategy')),
                ('contribution_percentage', models.FloatField(blank=True, help_text='Percentage of income contributed annually.', null=True, verbose_name='Contribution Percentage')),
                ('contribution_fixed_amount', models.FloatField(blank=True, help_text='Fixed amount contributed annually.', null=True, verbose_name='Contribution Fixed Amount')),
                ('description', models.TextField(blank=True, help_text='Description of the template for documentation purposes.', null=True, verbose_name='Template Description')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='edited_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Roth IRA Investment Configuration Template',
                'verbose_name_plural': 'Roth IRA Investment Configuration Templates',
            },
        ),
    ]
