# Generated by Django 5.1.4 on 2024-12-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_irainvestment_is_contribution_tax_deferred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='roth_ira_investments',
            field=models.ManyToManyField(related_name='plans', to='main.rothirainvestment', verbose_name='Roth IRA Investment Configurations'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='roth_ira_investment_templates',
            field=models.ManyToManyField(blank=True, related_name='plan_templates', to='main.rothirainvestmenttemplate', verbose_name='Roth IRA Investment Templates'),
        ),
    ]
