# Generated by Django 5.1.4 on 2025-01-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_irainvestment_income_rothirainvestment_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdeferredinvestmenttemplate',
            name='income',
        ),
    ]
