# Generated by Django 5.1.4 on 2025-01-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_taxdeferredinvestmenttemplate_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdeferredinvestment',
            name='income',
        ),
    ]
