# Generated by Django 5.1.4 on 2025-01-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_taxdeferredinvestment_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='growth_rate',
            field=models.FloatField(default=6, help_text='Annual Growth rate as a percentage.', verbose_name='Growth Rate'),
            preserve_default=False,
        ),
    ]
