# Generated by Django 5.1.4 on 2025-01-25 17:44

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_plan_growth_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='retirement_income_adjusted_for_inflation',
            field=models.BooleanField(default=True, help_text='Inflation adjusted for inflation.', verbose_name='Retirement Income Adjusted For Inflation'),
        ),
    ]
