# Generated by Django 5.1.4 on 2025-01-25 19:03

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_plan_retirement_income_adjusted_for_inflation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Manager Name')),
                ('manager_id', models.PositiveIntegerField(verbose_name='Manager ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='edited_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='main_comman_created_575133_idx'), models.Index(fields=['edited_at'], name='main_comman_edited__928ebc_idx'), models.Index(fields=['creator'], name='main_comman_creator_b9ee99_idx'), models.Index(fields=['editor'], name='main_comman_editor__8b85e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='edited_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_sequences', to='main.plan', verbose_name='Plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='main_comman_created_8243a2_idx'), models.Index(fields=['edited_at'], name='main_comman_edited__96b184_idx'), models.Index(fields=['creator'], name='main_comman_creator_e01514_idx'), models.Index(fields=['editor'], name='main_comman_editor__095406_idx')],
            },
        ),
    ]
