# Generated by Django 5.1.4 on 2025-02-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0034_command_commandsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandSequenceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='command',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='main_comman_created_575133_idx',
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='main_comman_edited__928ebc_idx',
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='main_comman_creator_b9ee99_idx',
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='main_comman_editor__8b85e4_idx',
        ),
        migrations.RemoveField(
            model_name='command',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='command',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='command',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='command',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='command',
            name='label',
        ),
        migrations.RemoveField(
            model_name='command',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='command',
            name='name',
        ),
        migrations.AddField(
            model_name='command',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandsequence',
            name='ordering_type',
            field=models.CharField(choices=[('predefined', 'Predefined'), ('custom', 'Custom')], default='custom', max_length=50, verbose_name='Ordering Type'),
        ),
        migrations.AddField(
            model_name='commandsequencecommand',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_instances', to='main.command'),
        ),
        migrations.AddField(
            model_name='commandsequencecommand',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_commands', to='main.commandsequence'),
        ),
        migrations.AlterUniqueTogether(
            name='commandsequencecommand',
            unique_together={('sequence', 'command')},
        ),
    ]
